services:
  influxdb:
    image: influxdb:2.5.1
    volumes:
    - ./.dev/influxdb:/var/lib/influxdb2
    ports:
    - 8086:8086

  datasink:
    image: krishnaiyer/datasink:0.1.0
    command: datasink -c /etc/config.yml
    restart: always
    ports:
      - "8080:8080"
      - "1883:1883"
    volumes:
      - ./config.yml:/etc/config.yml:ro
      - ./test.htpasswd:/etc/htpasswd:ro
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_COOKIE_SAMESITE=disabled
    volumes:
      - ./.dev/grafana:/var/lib/grafana
    depends_on:
      - influxdb
volumes:
  influxdb2:
