services:
  influxdb:
    image: influxdb:2.5.1
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: testuser
      DOCKER_INFLUXDB_INIT_PASSWORD: testpassword
      DOCKER_INFLUXDB_INIT_ORG: iot
      DOCKER_INFLUXDB_INIT_BUCKET: test_sensors
    volumes:
    - ./.dev/influxdb:/var/lib/influxdb2
volumes:
  influxdb2:
